#!/usr/bin/env ruby
# frozen_string_literal: true
require 'mqtt'
require 'tomlrb'

# Load configs
config = Tomlrb.load_file('secret.toml', symbolize_keys: true)
host = config[:config][:hostname]
port = config[:config][:port]
username = config[:credentials][:username]
password = config[:credentials][:password]

# Connect to MQTT broker
print '연결중 ... '
MQTT::Client.connect(host: host, port: port, username: username, password: password) do |c|
  puts "\e[32m완료!\e[0m"

  loop.with_index do |_, i|
    c.publish('test', "야호 #{i}")
    sleep 1
  end
end
