#!/usr/bin/env ruby
# frozen_string_literal: true
require 'mqtt'
require 'tomlrb'

# Load configs
config = Tomlrb.load_file('secret.toml', symbolize_keys: true)
host = config[:config][:hostname]
port = config[:config][:port]
username = config[:credentials][:username]
password = config[:credentials][:password]

# Connect to MQTT broker
MQTT::Client.connect(host: host, port: port, username: username, password: password) do |c|
  c.get('#') do |topic, message|
    puts "#{topic}: #{message}"
  end
end
